# Generated by Django 3.0.3 on 2020-03-03 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0002_auto_20200303_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='date_reading',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
