# Generated by Django 3.0.3 on 2020-03-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0003_auto_20200303_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='profile_image',
            field=models.ImageField(default='users.svg', upload_to='profile_image'),
        ),
    ]
