# Generated by Django 3.0.3 on 2020-03-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0006_auto_20200303_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='publication',
            field=models.CharField(choices=[('Watchtower', 'Watchtower'), ('Congregation Bible Study', 'Congregation Bible Study')], default='Needs to be set', max_length=30),
        ),
        migrations.AddField(
            model_name='reading',
            name='title',
            field=models.CharField(default='Needs to be set', max_length=120),
        ),
    ]
