# Generated by Django 3.0.3 on 2020-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readers', '0007_auto_20200304_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='email',
            field=models.EmailField(default='not set', max_length=254),
        ),
    ]
